### ISSUE TITLE
Navigate Command?

### ISSUE THREAD

**Issue by kkguo** [RootRobotics/root-robot-ble-protocol#13]
I cannot find the description for navigate command, but I guess it does exist because there is a response with command 17
[Command 17 - Navigate to Position Finished Response](https://github.com/iRobotEducation/root-robot-ble-protocol#command-17---navigate-to-position-finished-response)

**Comment by shamlian** [comment]
This will be more clear once #16 merges. I'll close this issue, then.

**Comment by shamlian** [comment]
Navigate command is now documented but not presently implemented in Root.
