### ISSUE TITLE
Doesn't work on a mac

### ISSUE THREAD

**Issue by janislejins** [RootRobotics/root-robot-ble-protocol#22]
Hi - I am working with some art students who are getting a slew of errors trying to run this BLE protocol.
Is the irobot_edu_sdk available to be downloaded and run locally?

**Comment by shamlian** [comment]
Hi there,

What software are you currently using that is giving you BLE protocol errors? This is a protocol description.

We do have a very early downloadable SDK available; please see [this issue](https://github.com/iRobotEducation/create3_docs/discussions/72#discussioncomment-2871621) for directions on how to get access.

**Comment by shamlian** [comment]
One thought -- if you're using the Python Web Playground (python.irobot.com), are you also using Chrome? My understanding is that Web Bluetooth does not work in Safari.

**Comment by shamlian** [comment]
It's been two weeks, so I'm going to close this issue. Please open a new one (or email us) if you're still having a problem.
