### ISSUE TITLE
Drive Arc command in staging protocol

### ISSUE THREAD

**Issue by entwanne** [RootRobotics/root-robot-ble-protocol#3]
Hi,

I'm using https://github.com/shamlian/root-robot-sdk to control my Root robot and was trying to use the drive arc command, that is listed here in the staging spec.
There is no effect and no response when I run the command.

I went deeper and sent raw data to the robot but I get nothing more.
I was trying the following packet as an example:

`[1, 27, 10, 0, 0, 2, 88, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 60]`

Is there something that I'm not doing well, or is it related to the staging state of the specification?

I have no problem with other commands, like drive distance (`[1, 8, 10, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 182]`).

Thanks

**Comment by entwanne** [comment]
Ok, it seems that my robot runs firmware 1.8 which only supports protocol 1.1.
Do you know how I can update it to firmware 1.11 without iphone app?

**Comment by mogenson** [comment]
Hello @entwanne!

Firmware version 1.11 is included in the current iOS App Store release of the Root Coding app: https://apps.apple.com/us/app/root-coding/id1153070718

Right now, the only way for customers to update firmware is through the iOS app. You're best bet is to find a friend with an iPhone or iPad.

We'll be supporting more platforms in the near future, and we'll be releasing firmware updates with more features. Note: the staging branch is for features that exist in the robot firmware, but do not yet have a graphical block in the coding app.

Take care!

**Comment by entwanne** [comment]
Ok thanks!
I'm a bit sad that there is no other way to do the update for now, I'll try to use motor speed commands to draw curves.
Regards.

**Comment by mogenson** [comment]
@entwanne You can now go to https://code.irobot.com. Connect to your robot, then press the play button and you will be prompted to update to a new firmware version that supports arc commands.

**Comment by entwanne** [comment]
Thanks, I'll retry it later. For the moment I couldn't manage to pair the robot with my browser.

**Comment by entwanne** [comment]
Hello,

I'm still stucked with this pairing issue and cannot find a solution.
I used chrome browser and enabled experimental web features, I can see my robot in `chrome://bluetooth-internals` and connect to it.
But when trying to pair the robot on https://code.irobot.com, no device is found. Is it a known issue?

Thanks.

**Comment by tinilk** [comment]
Hi Antoine,

Root doesn't use the standard pairing process for Bluetooth devices. Please try the instructions below:

In Chrome, navigate to http://code.irobot.com/ and click on a program or click the (+) icon to start a new program.
Click the "connect" icon on the title bar next to the program's name. (It looks like Root in a circle with a red X next to it.)
You should see your robot’s name appear in the connection window that opens, as shown in the linked picture below.
Click the robot’s name then click the "Pair" button:
![Root-pair](https://user-images.githubusercontent.com/4149719/97902160-2d7dd880-1d0b-11eb-8c61-3fd7d69d2a16.png)

After it's connected make sure the onscreen simulator panel is closed, so that your program runs on the real Root robot instead of running in the simulator.

Best regards,
Clint
The Root Team

**Comment by entwanne** [comment]
Thanks, I did exactly these steps, but I can't find my root robot in that pairing window, and I don't understand why as I can see the robot in the `bluetooth-internals`.

**Comment by tinilk** [comment]
Ok. Let's see if you can update the robot's software. That may have something to do with it.

With the robot off, hold in both the left & right bumpers, and press & hold the yellow nose to turn it on. Keep holding all 3 until the robot starts blinking blue. (The eye LEDs will remain off.)

While the robot is flashing blue, open this web page in Chrome and click the blue Pair button on the page: https://code.irobot.com/update/index.html
The small window that opens should show "ROOT BOOT". You should be able to click on ROOT BOOT then click the Pair button in the small window.

If it works, the robot will begin updating. It may take 10 minutes or so to complete the software update.
Once updated, you should now be able to connect from code.irobot.com using the previous instructions.

If you can't run the update, try connecting with another device that has a Chrome or Microsoft Edge browser instead (an Android phone, a different laptop etc.)

Best regards,
Clint

**Comment by entwanne** [comment]
Oh thanks, it's working! And all I wanted was to update the robot, thank you so much!

(and of course, the code.irobot.com pairing is now working)

**Comment by tinilk** [comment]
You're welcome! Glad that did it, and that the update worked.

Something else to keep in mind that my colleague just suggested to me, is that the robot won't show up as available to connect if you're already connected to it from another application. For example if you have a program using the SDK that's already connected though Bluetooth, it will prevent you being able to connect through code.irobot.com app.

Best regards,
Clint

**Comment by hapiel** [comment]
Hi @tinilk, I would like to update the firmware of my Root so I can use the arc command. The webpage https://code.irobot.com/update/index.html no longer exists, and if I run code from the browser I don't get prompted to update the firmware.
Is there a way?
Thanks

EDIT: nevermind, I did not realise it needs to be in boot mode and then connect to bluetooth over the web interface. I hope this comment helps someone some time

**Comment by miniBloq** [comment]
Hi @hapiel, yes you need the robot in Boot mode.
You can also force a firmware update by right-clicking in the BLE connection button as shown here:

<img width="1020" height="525" alt="Image" src="https://github.com/user-attachments/assets/86067b33-b5f7-4a8a-beed-fc7d80b2cf15" />
