### ISSUE TITLE
Command 0.11 - Get Enabled Events Response - Not Responding

### ISSUE THREAD

**Issue by shamlian** [RootRobotics/root-robot-ble-protocol#6]
Description from #5 as follows;

> ## Command 0.11 - Get Enabled Events Response
> 
> I always receive an empty bitfield from this command. The enable/disable event commands work but _Get enabled events_ keeps returning an empty bitfield.
> 
> Is this a known issue?

**Comment by shamlian** [comment]
I can confirm that 0.11 is not returning as expected; I will investigate this, soon. Thank you for the report.

**Comment by shamlian** [comment]
This is a bug and will be fixed in the next release; I will close the issue once we release the new firmware. Thank you again for the report and apologies for the trouble!

**Comment by entwanne** [comment]
Ok thanks!

**Comment by shamlian** [comment]
This should be fixed in 2.1!
